package com.stefanini.rest;

public enum Mensagem {

    ERRO_SALVAR_PESSOA("ERRO AO ADICIONAR PESSOA"),
    ERRO_REMOVER_PESSOA("ERRO AO REMOVER PESSOA"),
    ERRO_BUSCAR_PESSOAS("ERRO AO BUSCAR LISTA DE PESSOAS"),
    ERRO_BUSCAR_PESSOAS_PELO_ID("ERRO AO BUSCAR PESSOA, PELA ID DE PESSOA"),
    SUCESSO_SALVAR_PESSOA("CONSEGUIU ADICIONAR A PESSOA"),
    SUCESSO_REMOVER_PESSOA("ERRO AO REMOVER PESSOA"),

    ERRO_SALVAR_ENDERECO("ERRO AO ADICIONAR ENDEREÇO"),
    ERRO_SALVAR_PERFIL("ERRO AO ADICIONAR PERFIL"),
    ERRO_REMOVER_ENDERECO("ERRO AO REMOVER ENDEREÇO"),
    ERRO_REMOVER_PERFIL("ERRO AO REMOVER PERFIL"),
    SUCESSO_SALVAR_ENDERECO("CONSEGUIU ADICIONAR O ENDEREÇO"),
    SUCESSO_SALVAR_PERFIL("ERRO AO ADICIONAR PERFIL"),
    SUCESSO_REMOVER_ENDERECO("ERRO AO REMOVER ENDEREÇO"),
    SUCESSO_REMOVER_PERFIL("ERRO AO REMOVER PERFIL");

    private String texto;

    private Mensagem(String texto) {
        this.texto = texto;
    }

    public String getTexto() {
        return texto;
    }
}
